aws_region        = "us-east-1"
terraform_version = ">= 0.13.0"
vpc_id            = "vpc-e786dd9e"
ec2_subnet_id     = "subnet-fdd4d5b5"
ec2_pem_path      = "ekansh-ttn-infra"
pem_key_path      = "/home/ekansh/Downloads/ekansh-ttn-infra.pem"
ami_id            = "ami-0b0af3577fe5e3532"
ec2_instance_type = "t3.micro"
ec2_remote_user   = "ec2-user"
playbook_path     = "/home/ekansh/mediawiki-assignment/ansible/mediawiki-playbook.yml" 