variable "aws_region" {}
variable "terraform_version" {}
variable "vpc_id" {}
variable "ec2_pem_path" {}
variable "ec2_subnet_id" {}
variable "pem_key_path" {}
variable "playbook_path" {}
variable "ec2_instance_type" {}
variable "ami_id" {}
variable "ec2_remote_user" {}
